name:                calendar
version:             0.1.0.0
github:              "lsund/calendar"
license:             BSD3
author:              "Ludvig Sundström"
maintainer:          "lud.sund@gmail.com"
copyright:           "2018 Ludvig Sundström"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at ...

default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- parsec
- time
- old-locale
- Spock
- http-types
- text
- mtl
- lucid
- Spock-lucid
- protolude
- wai-middleware-static
- directory
- postgresql-simple
- curl
- aeson
- unordered-containers
- vector

library:
  source-dirs:
    - src

executables:
  calendar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calendar

# tests:
#   calendar-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - calendar
